### ISSUE TITLE
[Suggestion] Dynamic API Keys

### ISSUE THREAD

**Issue by shettytejas** [resend/resend-ruby#84]
I think it'd be a good idea to introduce dynamic API keys, which I'm assuming, can be done by making sure `Resend.api_key` accepts a Proc block.

This can be useful in applications, where developers want their users to bring their own Resend API keys.

Thoughts?

**Comment by drish** [comment]
@shettytejas that's an interesting use case, I think a proc would work. Another approach that i'm also working on and will be live soon will be something along these lines:

```ruby
# this currently doesn't work
client = Resend::ResendClient.new(api_key: "123")
client2 = Resend::ResendClient.new(api_key: "456")
```
